spring.application.name=ApiGatewayService
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

# Logging (optional)
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO

management.endpoints.web.exposure.include=health,info,gateway
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

spring.main.web-application-type=reactive
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedorigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations[/**].exposedHeaders=Authorization
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations[/**].allowCredentials=true
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE


spring.cloud.gateway.server.webflux.routes[0].id=EUREKA
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/eureka
spring.cloud.gateway.server.webflux.routes[0].filters[0]=SetPath=/

spring.cloud.gateway.server.webflux.routes[1].id=EUREKA-STATIC-RESOURCES
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/eureka/**

spring.cloud.gateway.server.webflux.routes[2].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth/**,/api/profile/**

spring.cloud.gateway.server.webflux.routes[3].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webflux.routes[4].id=INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.server.webflux.routes[5].id=ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/orders/**,/api/sales/**

spring.cloud.gateway.server.webflux.routes[6].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/payment/**
