spring.application.name=PAYMENT-SERVICE
server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id="${spring.application.name}:${random.uuid}"
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.openfeign.httpclient.enabled=true




spring.datasource.url=#database_url
spring.datasource.username=#database_username
spring.datasource.password=#database_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

stripe.secretkey=#Stripe_secret_key

jwt.secret=#JWT_secret_key
jwt.expiration=18000

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=#activeMQ_user_name
spring.activemq.password=#activeMQ_password
jms.pub-sub-domain=false

