spring.application.name=PRODUCT-SERVICE
server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id="${spring.application.name}:${random.uuid}"
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.openfeign.httpclient.enabled=true



spring.data.mongodb.uri=#database_url
spring.data.mongodb.database=Instabuy
spring.data.mongodb.auto-index-creation=true

jwt.secret=#JWT_secret_key
jwt.expiration=86400000